# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://bla15e.github.io/avalanchepy/"

git_url = "https://github.com/bla15e/avalanchepy/tree/{branch}/"

def custom_doc_links(name): return None
